// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Projects.Infrastructure.Persistence;

#nullable disable

namespace Projects.API.Migrations
{
    [DbContext(typeof(ProjectsDbContext))]
    [Migration("20260207151122_SyncModelChanges")]
    partial class SyncModelChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("projects")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Projects.Domain.Entities.Cabinet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssemblyId")
                        .HasColumnType("uuid")
                        .HasColumnName("assembly_id");

                    b.Property<decimal?>("CalculatedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("calculated_price");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EdgeId")
                        .HasColumnType("uuid")
                        .HasColumnName("edge_id");

                    b.Property<string>("FacadeType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("facade_type");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ParameterOverrides")
                        .HasColumnType("jsonb")
                        .HasColumnName("parameter_overrides");

                    b.Property<string>("PlacementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("placement_type");

                    b.Property<double>("PositionX")
                        .HasColumnType("double precision")
                        .HasColumnName("position_x");

                    b.Property<double>("PositionY")
                        .HasColumnType("double precision")
                        .HasColumnName("position_y");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<double>("Rotation")
                        .HasColumnType("double precision")
                        .HasColumnName("rotation");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("ZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.HasIndex("AssemblyId");

                    b.HasIndex("EdgeId");

                    b.HasIndex("RoomId");

                    b.HasIndex("ZoneId");

                    b.ToTable("cabinets", "projects");
                });

            modelBuilder.Entity("Projects.Domain.Entities.CabinetPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CabinetId")
                        .HasColumnType("uuid")
                        .HasColumnName("cabinet_id");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid")
                        .HasColumnName("component_id");

                    b.Property<string>("Condition")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("condition");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<Guid?>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<string>("Provides")
                        .HasColumnType("jsonb")
                        .HasColumnName("provides");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.Property<string>("QuantityFormula")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("quantity_formula");

                    b.Property<double>("RotationX")
                        .HasColumnType("double precision")
                        .HasColumnName("rotation_x");

                    b.Property<double>("RotationY")
                        .HasColumnType("double precision")
                        .HasColumnName("rotation_y");

                    b.Property<double>("RotationZ")
                        .HasColumnType("double precision")
                        .HasColumnName("rotation_z");

                    b.Property<string>("Shape")
                        .HasColumnType("jsonb")
                        .HasColumnName("shape");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid?>("SourceAssemblyPartId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_assembly_part_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("X")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("x");

                    b.Property<string>("Y")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("y");

                    b.Property<string>("Z")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("z");

                    b.HasKey("Id");

                    b.HasIndex("CabinetId");

                    b.HasIndex("SourceAssemblyPartId");

                    b.ToTable("cabinet_parts", "projects");
                });

            modelBuilder.Entity("Projects.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("QuestionnaireData")
                        .HasColumnType("jsonb")
                        .HasColumnName("questionnaire_data");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("UserId");

                    b.ToTable("projects", "projects");
                });

            modelBuilder.Entity("Projects.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CeilingHeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2700)
                        .HasColumnName("ceiling_height");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("rooms", "projects");
                });

            modelBuilder.Entity("Projects.Domain.Entities.RoomEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EndVertexId")
                        .HasColumnType("uuid")
                        .HasColumnName("end_vertex_id");

                    b.Property<bool>("HasDoor")
                        .HasColumnType("boolean")
                        .HasColumnName("has_door");

                    b.Property<bool>("HasWindow")
                        .HasColumnType("boolean")
                        .HasColumnName("has_window");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<Guid>("StartVertexId")
                        .HasColumnType("uuid")
                        .HasColumnName("start_vertex_id");

                    b.Property<int>("WallHeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2700)
                        .HasColumnName("wall_height");

                    b.HasKey("Id");

                    b.HasIndex("EndVertexId");

                    b.HasIndex("RoomId");

                    b.HasIndex("StartVertexId");

                    b.ToTable("room_edges", "projects");
                });

            modelBuilder.Entity("Projects.Domain.Entities.RoomVertex", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<double>("X")
                        .HasColumnType("double precision")
                        .HasColumnName("x");

                    b.Property<double>("Y")
                        .HasColumnType("double precision")
                        .HasColumnName("y");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("room_vertices", "projects");
                });

            modelBuilder.Entity("Projects.Domain.Entities.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EdgeId")
                        .HasColumnType("uuid")
                        .HasColumnName("edge_id");

                    b.Property<double>("EndX")
                        .HasColumnType("double precision")
                        .HasColumnName("end_x");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<double>("StartX")
                        .HasColumnType("double precision")
                        .HasColumnName("start_x");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("EdgeId");

                    b.ToTable("zones", "projects");
                });

            modelBuilder.Entity("Projects.Domain.Entities.Cabinet", b =>
                {
                    b.HasOne("Projects.Domain.Entities.RoomEdge", null)
                        .WithMany()
                        .HasForeignKey("EdgeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Projects.Domain.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projects.Domain.Entities.Zone", null)
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Projects.Domain.Entities.CabinetPart", b =>
                {
                    b.HasOne("Projects.Domain.Entities.Cabinet", null)
                        .WithMany()
                        .HasForeignKey("CabinetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Projects.Domain.Entities.Room", b =>
                {
                    b.HasOne("Projects.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Projects.Domain.Entities.RoomEdge", b =>
                {
                    b.HasOne("Projects.Domain.Entities.RoomVertex", null)
                        .WithMany()
                        .HasForeignKey("EndVertexId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Projects.Domain.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projects.Domain.Entities.RoomVertex", null)
                        .WithMany()
                        .HasForeignKey("StartVertexId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Projects.Domain.Entities.RoomVertex", b =>
                {
                    b.HasOne("Projects.Domain.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Projects.Domain.Entities.Zone", b =>
                {
                    b.HasOne("Projects.Domain.Entities.RoomEdge", null)
                        .WithMany()
                        .HasForeignKey("EdgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
